### ISSUE TITLE
./compile is missing

### ISSUE THREAD

**Issue by martin-ueding** [usqcd-software/qmt#1]
Other repositories like `chroma` and `qdpxx` contain a `autogen.sh`. This repository does not have the file. Those `autogen.sh` contain only `autoreconf -f`. While building a RPM package for `qmt`, I have just used `autoreconf -f` before `./configure`. That did not work out, however:

```
+ autoreconf -f                                                                                                        
configure.ac:6: error: required file './compile' not found                                                             
configure.ac:6:   'automake --add-missing' can install 'compile'                                                       
automake: warnings are treated as errors                                                                               
/usr/share/automake-1.15/am/library.am: warning: 'libqmt.a': linking libraries using a non-POSIX                       
/usr/share/automake-1.15/am/library.am: archiver requires 'AM_PROG_AR' in 'configure.ac'                               
src/Makefile.am:1:   while processing library 'libqmt.a'                                                               
parallel-tests: error: required file './test-driver' not found                                                         
parallel-tests:   'automake --add-missing' can install 'test-driver'                                                   
autoreconf: automake failed with exit status: 1  
```

I think that the file `./compile` was created locally and not checked into the git repository?

Running `./configure` directly generates a `Makefile`. My knowledge of the GNU Build System is limited, but should the `./configure` script really be included in the git repository? Would it be better to add this `./compile` and let the user do `autoreconf -f`?

**Comment by grokqcd** [comment]
Fixed.

BTW, I’m not aware of any part of the usqcd-software that is currently using qmt. QDPXX no longer uses it. Of course, the older commits of QDPXX will use QMT so the repo. is retained.

```
    Robert
```

**Comment by martin-ueding** [comment]
I see, so QMT is deprecated in favor of OpenMP in general?

In that case I can just replace `--with-qmt=<DIR>` with `--enable-openmp`, adjust the `CXXFLAGS` and have SMT enabled, right? This makes compilation even easier and I need one RPM package less :smile:.

**Comment by grokqcd** [comment]
Hi Martin,
   Indeed, QMT is deprecated. And yes, we've moved to OpenMP using the flags you've suggested.
